/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author lenovo
 */
public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public FrameMain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbQuanLySanPham = new javax.swing.JLabel();
        lbQuanLyMauSac = new javax.swing.JLabel();
        lbQuanLyThuongHieu = new javax.swing.JLabel();
        lbQuanLyChatLieu = new javax.swing.JLabel();
        lbQuanLyHinhDang = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ BÁN HÀNG");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlbQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbQuanLySanPham.setText("Quản lý sản phẩm");
        jlbQuanLySanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbQuanLySanPhamMouseClicked(evt);
            }
        });

        lbQuanLyMauSac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbQuanLyMauSac.setText("Quản lý màu sắc");
        lbQuanLyMauSac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQuanLyMauSacMouseClicked(evt);
            }
        });

        lbQuanLyThuongHieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbQuanLyThuongHieu.setText("Quản lý thương hiệu");
        lbQuanLyThuongHieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQuanLyThuongHieuMouseClicked(evt);
            }
        });

        lbQuanLyChatLieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbQuanLyChatLieu.setText("Quản lý chất liệu");
        lbQuanLyChatLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQuanLyChatLieuMouseClicked(evt);
            }
        });

        lbQuanLyHinhDang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbQuanLyHinhDang.setText("Quản lý hình dạng");
        lbQuanLyHinhDang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQuanLyHinhDangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbQuanLySanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbQuanLyThuongHieu, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
            .addComponent(lbQuanLyMauSac, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
            .addComponent(lbQuanLyChatLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
            .addComponent(lbQuanLyHinhDang, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlbQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbQuanLyHinhDang, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lbQuanLyMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbQuanLyThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbQuanLyChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/kinhBGR.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbQuanLySanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLySanPhamMouseClicked
        JFrameSP frameSP = new JFrameSP();
        frameSP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlbQuanLySanPhamMouseClicked

    private void lbQuanLyHinhDangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuanLyHinhDangMouseClicked
       this.setVisible(false);
       new FrameHinhDang().setVisible(true);
    }//GEN-LAST:event_lbQuanLyHinhDangMouseClicked

    private void lbQuanLyChatLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuanLyChatLieuMouseClicked
        new FrameChatLieu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbQuanLyChatLieuMouseClicked

    private void lbQuanLyMauSacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuanLyMauSacMouseClicked
        new FrameMauSac().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbQuanLyMauSacMouseClicked

    private void lbQuanLyThuongHieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuanLyThuongHieuMouseClicked
        this.setVisible(false);
        new FrameThuongHieu().setVisible(true);
    }//GEN-LAST:event_lbQuanLyThuongHieuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlbQuanLySanPham;
    private javax.swing.JLabel lbQuanLyChatLieu;
    private javax.swing.JLabel lbQuanLyHinhDang;
    private javax.swing.JLabel lbQuanLyMauSac;
    private javax.swing.JLabel lbQuanLyThuongHieu;
    // End of variables declaration//GEN-END:variables
}
